name: rwd4drug
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.1
  - numpy=1.19.4
  - pandas=1.2.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - tqdm=4.54.1
  - pip=20.3.1
  - pip:
    - xlsxwriter==1.3.8
    - xgboost==1.4.2
    - lightgbm==3.2.1
    - lifelines==0.26.0

