mkdir -p output/simulate/LR/log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S3D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 4 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S4D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 5 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S5D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 6 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S6D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 7 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S7D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 8 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S8D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 9 2>&1 | tee output/simulate/LR/log/simun2500train0.80_S9D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S3D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 4 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S4D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 5 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S5D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 6 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S6D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 7 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S7D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 8 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S8D267_LR.log
python main_revise_testset_simulate.py --nsim 2500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 9 2>&1 | tee output/simulate/LR/log/simun2500train0.60_S9D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S3D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 4 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S4D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 5 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S5D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 6 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S6D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 7 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S7D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 8 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S8D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 9 2>&1 | tee output/simulate/LR/log/simun3000train0.80_S9D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S3D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 4 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S4D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 5 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S5D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 6 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S6D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 7 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S7D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 8 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S8D267_LR.log
python main_revise_testset_simulate.py --nsim 3000 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 9 2>&1 | tee output/simulate/LR/log/simun3000train0.60_S9D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S3D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 4 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S4D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 5 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S5D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 6 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S6D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 7 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S7D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 8 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S8D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.8 --run_model LR --output_dir output/simulate/LR/ --random_seed 9 2>&1 | tee output/simulate/LR/log/simun3500train0.80_S9D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 0 2>&1 | tee output/simulate/LR/log/simun3500train0.60_S0D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 1 2>&1 | tee output/simulate/LR/log/simun3500train0.60_S1D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 2 2>&1 | tee output/simulate/LR/log/simun3500train0.60_S2D267_LR.log
python main_revise_testset_simulate.py --nsim 3500 --train_ratio 0.6 --run_model LR --output_dir output/simulate/LR/ --random_seed 3 2>&1 | tee output/simulate/LR/log/simun3500train0.60_S3D267_LR.log
